### ISSUE TITLE
Composer SecurityException

### ISSUE THREAD

**Issue by Mato-Z** [zecure/shadowd_ui#1]
Hello,
I have been installing shadowd_ui according to this procedure https://shadowd.zecure.org/overview/user_interface/, but when I run php composer.phar install it ends with this error:

[Composer\Repository\RepositorySecurityException]                                                                                                                         
  The contents of http://packagist.org/p/provider-latest$f57dede90e13883cab0a07845e0cb2dc9dc7aed48e4716c90900f83758401348.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.        

Can you help me please?
Thank you.

**Comment by zit-hb** [comment]
Hey Mato,

according to [https://github.com/composer/composer/issues/1431](this) you probably had a conflict with the cron jobs that update the packages at packagist. Try installing it again.

**Comment by Mato-Z** [comment]
Hello zit-hb, thanks for reply! It is very interesting, but when I changed location from my house to my office it works correctly... I use Linux Debian 8 and I have compiled it manually...

**Comment by zit-hb** [comment]
Oh oh, maybe you should start tunnelling your home network through a VPN ^_^
