### ISSUE TITLE
Composer could not find a composer.json file

### ISSUE THREAD

**Issue by talhakabakus** [zecure/shadowd_ui#21]
Getting the error `composer could not find a composer.json file` when I try to execute the command `php composer.phar install`. I have followed the instructions and executed the command `curl -s https://getcomposer.org/installer | php` first.

p.s. Using Ubuntu Server 16.04

**Comment by zit-hb** [comment]
Well, is there a composer.json file in the directory you are in when executing the command? This should be the content of that directory: https://github.com/zecure/shadowd_ui

**Comment by talhakabakus** [comment]
Just copied the `composer.json` file which is located in the root directory. Thanks for your help.
